<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Permitir la localization de toda la app -->
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Blazorise" Version="2.0.3" />
		<PackageReference Include="Blazorise.Bootstrap" Version="2.0.3" />
		<PackageReference Include="Blazorise.Icons.FontAwesome" Version="2.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.3.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.5" />
		<PackageReference Include="Radzen.Blazor" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\SolarBlazorDocs\Fuentes\SolarBlazorDocs.Browser\SolarBlazorDocs.Browser.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Shared\Resources\AllResourcesRes.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>AllResourcesRes.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Shared\Resources\AllResourcesRes.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>AllResourcesRes.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>

</Project>
